In [1]:
import torch

In [6]:
torch.__version__

'1.3.0'

Input:  A 2D tensor of size 3x10, that contains random integers in therange [0,99]

In [44]:
my_input = torch.randint(0,100,(3,10))
my_input

tensor([[85,  1, 62, 59, 76, 34, 69, 72, 78, 69],
        [36, 60, 89, 68, 54, 46, 39,  8,  1, 95],
        [35, 93, 45, 74, 17, 94, 69, 60, 33, 37]])

Inputembeddings:  A 3D tensor that contains random float values ofsize 3x10x20

In [42]:
inputembeddings = torch.randn(3,10,20)
inputembeddings[:1]

tensor([[[-0.3117, -0.1817,  0.6998, -0.3112, -1.3889,  0.3545, -0.5465,
          -0.6597, -0.4568,  0.1219,  0.0302,  0.2615,  0.4841, -1.3054,
          -1.5677, -0.3988, -1.5334, -1.2977, -2.1492, -1.1823],
         [-0.6397, -0.2966,  1.4126,  0.4218,  1.4281, -0.6092, -0.2476,
          -0.5829,  0.3307, -1.7473, -0.2635, -0.4425,  0.4102,  0.5573,
           0.1610, -0.5105,  1.3517,  0.4150, -0.0855, -0.4956],
         [-0.0319,  1.9651,  0.9148,  0.6354,  0.3323,  0.0216,  0.6575,
          -0.0435, -0.3293, -0.7240,  0.6402,  0.5331, -0.4781, -0.6983,
          -0.4217, -0.0140, -0.9150, -0.5700,  1.0325, -0.0511],
         [ 0.9623,  0.3251,  0.1224,  2.2061,  0.3710, -0.2295,  0.3238,
           1.5964,  0.4070, -0.2977,  0.4808, -1.0648, -0.4462, -0.1746,
           0.7315,  0.6617, -0.7365, -1.4647, -1.1183, -2.3931],
         [-1.0494, -1.2023,  1.9146, -1.4302,  1.4475,  0.2225,  0.7362,
           1.5685, -1.0635,  2.0726,  1.0386, -0.5941,  0.9425,  0.3255,
          

input1hot:  Create a 1-hot vector tensor from ”Input” tensor; thiswould be of size 3x10x100

We have 3 sentences, 10 words each. Vocabulary size is 100. 

=> class count is 100 (each word in the vocabulary is one class)

`input1hot = torch.eye(class_count)[input_tensor, :]`

In [18]:
input1hot = torch.eye(100)[my_input,:]
# input1hot
# input1hot[0]

Change the shape of a tensor: T=torch.rand(3,4,5) to T_changed of size (12x5)


In [20]:
T = torch.rand(3,4,5)
T

tensor([[[0.2802, 0.1092, 0.3007, 0.3440, 0.1079],
         [0.1693, 0.6959, 0.8709, 0.8511, 0.8845],
         [0.3884, 0.5370, 0.2518, 0.5845, 0.3406],
         [0.3556, 0.8804, 0.6337, 0.2685, 0.4167]],

        [[0.4144, 0.0738, 0.0207, 0.1880, 0.0858],
         [0.2792, 0.3351, 0.5531, 0.7231, 0.8246],
         [0.0068, 0.5357, 0.2224, 0.7188, 0.3783],
         [0.6597, 0.7907, 0.9459, 0.6324, 0.5326]],

        [[0.4448, 0.5895, 0.5237, 0.7999, 0.7261],
         [0.5330, 0.7934, 0.0593, 0.7538, 0.9823],
         [0.8882, 0.3721, 0.2482, 0.4794, 0.9387],
         [0.1857, 0.0242, 0.1253, 0.4624, 0.4543]]])

In [23]:
T_changed = T.reshape(12,5)
T_changed

tensor([[0.2802, 0.1092, 0.3007, 0.3440, 0.1079],
        [0.1693, 0.6959, 0.8709, 0.8511, 0.8845],
        [0.3884, 0.5370, 0.2518, 0.5845, 0.3406],
        [0.3556, 0.8804, 0.6337, 0.2685, 0.4167],
        [0.4144, 0.0738, 0.0207, 0.1880, 0.0858],
        [0.2792, 0.3351, 0.5531, 0.7231, 0.8246],
        [0.0068, 0.5357, 0.2224, 0.7188, 0.3783],
        [0.6597, 0.7907, 0.9459, 0.6324, 0.5326],
        [0.4448, 0.5895, 0.5237, 0.7999, 0.7261],
        [0.5330, 0.7934, 0.0593, 0.7538, 0.9823],
        [0.8882, 0.3721, 0.2482, 0.4794, 0.9387],
        [0.1857, 0.0242, 0.1253, 0.4624, 0.4543]])

Matrix multiply two 2-D tensors: of sizes 3x5 and 5x6

In [24]:
m1 = torch.randint(0,10,(3,5))
m2 = torch.randint(0,10,(5,6))
torch.matmul(m1,m2)

tensor([[137,  96,  44,  93, 103,  81],
        [ 36,  74,  27,  82,  23,  29],
        [114, 144,  69,  86,  71,  69]])

In [25]:
m1@m2

tensor([[137,  96,  44,  93, 103,  81],
        [ 36,  74,  27,  82,  23,  29],
        [114, 144,  69,  86,  71,  69]])

In [26]:
torch.mm(m1,m2)

tensor([[137,  96,  44,  93, 103,  81],
        [ 36,  74,  27,  82,  23,  29],
        [114, 144,  69,  86,  71,  69]])

Difference between `mm` and `matmul`: `mm` does not support broadcasting. More info: https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics

Matrix multiply two 4-D tensors on the last 2 dimensions: of size 2x2x3x5 and 2x2x5x6

In [31]:
m3 = torch.randint(0,10,(2,2,3,5))
m4 = torch.randint(0,10,(2,2,5,6))
torch.matmul(m3,m4) # torch.mm() would not work, but m3@m4 works

tensor([[[[129, 103,  97, 104,  88, 112],
          [ 97,  75,  78,  91,  65,  92],
          [177, 118, 129, 135,  98, 123]],

         [[161,  63,  72, 119, 103, 168],
          [ 98,  28,  53,  76,  86, 122],
          [123,  35,  64,  91,  98, 137]]],


        [[[ 44,  40,  60,  55,  22,  31],
          [ 88,  64,  87,  93,  51,  69],
          [ 67,  54,  88,  91,  58,  59]],

         [[132, 142, 127,  77, 105, 120],
          [ 81,  71,  70,  41,  56,  62],
          [150, 148, 140, 114, 130, 133]]]])

In [34]:
m3

tensor([[[[4, 3, 7, 3, 2],
          [5, 3, 4, 3, 0],
          [3, 1, 9, 8, 4]],

         [[8, 1, 5, 8, 9],
          [2, 9, 0, 0, 6],
          [4, 9, 0, 1, 7]]],


        [[[2, 0, 5, 0, 2],
          [4, 0, 5, 3, 3],
          [1, 1, 7, 3, 3]],

         [[4, 3, 9, 5, 7],
          [3, 4, 7, 1, 1],
          [9, 9, 9, 2, 4]]]])

Transpose 2 dimensions of tensors

In [33]:
torch.transpose(m3, 1, 3)

tensor([[[[4, 8],
          [5, 2],
          [3, 4]],

         [[3, 1],
          [3, 9],
          [1, 9]],

         [[7, 5],
          [4, 0],
          [9, 0]],

         [[3, 8],
          [3, 0],
          [8, 1]],

         [[2, 9],
          [0, 6],
          [4, 7]]],


        [[[2, 4],
          [4, 3],
          [1, 9]],

         [[0, 3],
          [0, 4],
          [1, 9]],

         [[5, 9],
          [5, 7],
          [7, 9]],

         [[0, 5],
          [3, 1],
          [3, 2]],

         [[2, 7],
          [3, 1],
          [3, 4]]]])

In [36]:
m5 = torch.randint(0,10,(2,3,4))
m5

tensor([[[5, 0, 6, 3],
         [5, 8, 3, 3],
         [5, 5, 7, 0]],

        [[1, 6, 3, 9],
         [4, 8, 8, 9],
         [9, 1, 8, 0]]])

In [38]:
torch.transpose(m5, 1, 2)

tensor([[[5, 5, 5],
         [0, 8, 5],
         [6, 3, 7],
         [3, 3, 0]],

        [[1, 4, 9],
         [6, 8, 1],
         [3, 8, 8],
         [9, 9, 0]]])

### City hop problem

Find the number of cities that you can go in 3 hops

In [41]:
adjacency_matrix = torch.Tensor([[0,0,1,0,1,0],
                                 [0,0,1,1,1,0],
                                 [1,1,0,1,1,0],
                                 [0,1,1,0,1,1],
                                 [1,1,1,1,0,0],
                                 [0,0,0,1,0,0]])