In [1]:
import torch

In [2]:
torch.__version__

'1.3.0'

Input:  A 2D tensor of size 3x10, that contains random integers in therange [0,99]

In [3]:
my_input = torch.randint(0,100,(3,10))
my_input

tensor([[65, 84,  5, 83, 44, 79,  5, 45, 16,  0],
        [28, 45, 19, 99, 48, 53, 31, 23, 49,  9],
        [69, 62, 78,  1,  2, 34,  0, 92, 54, 86]])

Inputembeddings:  A 3D tensor that contains random float values ofsize 3x10x20

In [5]:
inputembeddings = torch.randn(3,10,20)
#inputembeddings[:1]

input1hot:  Create a 1-hot vector tensor from ”Input” tensor; this would be of size 3x10x100

We have 3 sentences, 10 words each. Vocabulary size is 100. 

=> class count is 100 (each word in the vocabulary is one class)

`input1hot = torch.eye(class_count)[input_tensor, :]`

In [6]:
input1hot = torch.eye(100)[my_input,:]
# input1hot
# input1hot[0]

Change the shape of a tensor: T=torch.rand(3,4,5) to T_changed of size (12x5)


In [7]:
T = torch.rand(3,4,5)
T

tensor([[[0.6402, 0.6079, 0.8559, 0.9899, 0.1133],
         [0.7838, 0.9328, 0.1422, 0.5809, 0.6702],
         [0.7345, 0.0750, 0.4144, 0.6704, 0.1514],
         [0.4052, 0.8533, 0.9094, 0.4372, 0.7960]],

        [[0.3095, 0.8514, 0.5035, 0.3453, 0.1030],
         [0.5723, 0.2385, 0.0040, 0.7973, 0.0646],
         [0.4091, 0.9444, 0.4822, 0.7767, 0.5291],
         [0.2507, 0.5114, 0.4741, 0.4386, 0.4640]],

        [[0.8668, 0.1613, 0.1211, 0.8154, 0.0641],
         [0.3213, 0.3829, 0.2390, 0.1646, 0.3332],
         [0.6857, 0.3095, 0.2883, 0.9370, 0.7136],
         [0.0830, 0.5468, 0.0630, 0.3813, 0.6963]]])

In [8]:
T_changed = T.reshape(12,5)
T_changed

tensor([[0.6402, 0.6079, 0.8559, 0.9899, 0.1133],
        [0.7838, 0.9328, 0.1422, 0.5809, 0.6702],
        [0.7345, 0.0750, 0.4144, 0.6704, 0.1514],
        [0.4052, 0.8533, 0.9094, 0.4372, 0.7960],
        [0.3095, 0.8514, 0.5035, 0.3453, 0.1030],
        [0.5723, 0.2385, 0.0040, 0.7973, 0.0646],
        [0.4091, 0.9444, 0.4822, 0.7767, 0.5291],
        [0.2507, 0.5114, 0.4741, 0.4386, 0.4640],
        [0.8668, 0.1613, 0.1211, 0.8154, 0.0641],
        [0.3213, 0.3829, 0.2390, 0.1646, 0.3332],
        [0.6857, 0.3095, 0.2883, 0.9370, 0.7136],
        [0.0830, 0.5468, 0.0630, 0.3813, 0.6963]])

Matrix multiply two 2-D tensors: of sizes 3x5 and 5x6

In [9]:
m1 = torch.randint(0,10,(3,5))
m2 = torch.randint(0,10,(5,6))
torch.matmul(m1,m2)

tensor([[ 40,  44,   6,  28,  34,  16],
        [159, 199,  78, 156, 205, 127],
        [ 56,  69,  32,  61,  78,  51]])

In [12]:
m1@m2

tensor([[ 40,  44,   6,  28,  34,  16],
        [159, 199,  78, 156, 205, 127],
        [ 56,  69,  32,  61,  78,  51]])

In [14]:
torch.mm(m1,m2)

tensor([[ 40,  44,   6,  28,  34,  16],
        [159, 199,  78, 156, 205, 127],
        [ 56,  69,  32,  61,  78,  51]])

Difference between `mm` and `matmul`: `mm` does not support broadcasting. More info: https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics

Matrix multiply two 4-D tensors on the last 2 dimensions: of size 2x2x3x5 and 2x2x5x6

In [16]:
m3 = torch.randint(0,10,(2,2,3,5))
m4 = torch.randint(0,10,(2,2,5,6))
torch.matmul(m3,m4) # torch.mm() would not work, but m3@m4 works

tensor([[[[ 83, 152, 135, 130,  94, 166],
          [106, 149, 129, 132,  94, 156],
          [123,  55,  46,  59,  92,  43]],

         [[ 44,  42,  33,  56,  95,  62],
          [ 75,  79, 102, 106, 117, 115],
          [112,  49,  82,  55,  87,  96]]],


        [[[127, 127,  78, 109,  99, 122],
          [ 84,  68,  34, 126, 125, 102],
          [117,  74,  50, 112, 111, 105]],

         [[126, 174, 163, 116, 103, 152],
          [ 58,  99,  53,  64,  39,  43],
          [ 81, 100, 109,  95,  73,  58]]]])

In [17]:
m3

tensor([[[[8, 7, 1, 9, 3],
          [8, 7, 4, 7, 2],
          [4, 1, 9, 0, 4]],

         [[3, 5, 0, 6, 0],
          [8, 0, 3, 7, 4],
          [3, 0, 8, 1, 7]]],


        [[[1, 3, 4, 5, 7],
          [9, 2, 7, 0, 3],
          [7, 0, 5, 1, 8]],

         [[8, 7, 8, 5, 8],
          [4, 5, 1, 5, 0],
          [9, 4, 0, 5, 6]]]])

Transpose 2 dimensions of tensors

In [18]:
torch.transpose(m3, 1, 3)

tensor([[[[8, 3],
          [8, 8],
          [4, 3]],

         [[7, 5],
          [7, 0],
          [1, 0]],

         [[1, 0],
          [4, 3],
          [9, 8]],

         [[9, 6],
          [7, 7],
          [0, 1]],

         [[3, 0],
          [2, 4],
          [4, 7]]],


        [[[1, 8],
          [9, 4],
          [7, 9]],

         [[3, 7],
          [2, 5],
          [0, 4]],

         [[4, 8],
          [7, 1],
          [5, 0]],

         [[5, 5],
          [0, 5],
          [1, 5]],

         [[7, 8],
          [3, 0],
          [8, 6]]]])

In [19]:
m5 = torch.randint(0,10,(2,3,4))
m5

tensor([[[9, 2, 3, 1],
         [9, 8, 5, 5],
         [4, 0, 7, 2]],

        [[5, 5, 0, 8],
         [7, 1, 4, 2],
         [0, 5, 3, 5]]])

In [20]:
torch.transpose(m5, 1, 2)

tensor([[[9, 9, 4],
         [2, 8, 0],
         [3, 5, 7],
         [1, 5, 2]],

        [[5, 7, 0],
         [5, 1, 5],
         [0, 4, 3],
         [8, 2, 5]]])

### City hop problem

Find the number of cities that you can go in 3 hops

In [21]:
adjacency_matrix = torch.Tensor([[0,0,1,0,1,0],
                                 [0,0,1,1,1,0],
                                 [1,1,0,1,1,0],
                                 [0,1,1,0,1,1],
                                 [1,1,1,1,0,0],
                                 [0,0,0,1,0,0]])

### Creating modules

Create a linear layer module and check forward pass

In [53]:
import torch.nn as nn # frem here you can get layers
from torch.nn import functional as F # from here you can get (activation) functions

In [59]:
class MyLinearNN(nn.Module):
    def __init__(self, input_size):
        super(MyLinearNN, self).__init__()
        # define the layers here
        self.layer_1 = nn.Linear(input_size, 4)
        self.layer_2 = nn.Linear(4, 3)
        self.layer_3 = nn.Linear(3, 1)
        
    def forward(self, x):
        # apply functions here
        # execute the chain of layers and functions
        x = torch.sigmoid(self.layer_1(x)) # (I got a warning that F.sigmoid is deprecated)
        x = F.tanh(self.layer_2(x))
        x = F.relu(self.layer_3(x))
        return x

Make Dummy data again: 3 "batches" of 10 samples each where each sample has an input size of 20.
So one sample is 20 random numbers.

In [60]:
inputembeddings = torch.randn(3,10,20) # dummy data, like above

In [61]:
my_net = MyLinearNN(20) # input size is 20
for x in inputembeddings[0]: # this is the first of three batches
    y = my_net.forward(x)
    print(y)

tensor([0.1610], grad_fn=<ReluBackward0>)
tensor([0.2727], grad_fn=<ReluBackward0>)
tensor([0.0846], grad_fn=<ReluBackward0>)
tensor([0.0309], grad_fn=<ReluBackward0>)
tensor([0.1060], grad_fn=<ReluBackward0>)
tensor([0.1912], grad_fn=<ReluBackward0>)
tensor([0.2384], grad_fn=<ReluBackward0>)
tensor([0.2308], grad_fn=<ReluBackward0>)
tensor([0.], grad_fn=<ReluBackward0>)
tensor([0.2163], grad_fn=<ReluBackward0>)
